;;; steven-templates.el --- Simple text templates with consult  -*- lexical-binding: t -*-

;; Author: Steven
;; Version: 0.1
;; Package-Requires: ((emacs "28.1") (consult "0.35"))
;; Keywords: convenience, templates
;; URL: https://github.com/StevenFolkersma/consult-template.git

;;; Commentary:

;; A lightweight alternative to yasnippet for simple, static text templates.
;; Templates are plain strings — no snippet syntax, no expansion logic — just
;; text you want to insert quickly.
;;
;; Templates are selected via `consult', which provides live preview of the
;; template body as you narrow, and annotation showing a truncated preview in
;; the margin.
;;
;; Usage:
;;
;;   M-x steven-template-insert   — pick a template and insert it at point
;;   M-x steven-template-define   — define a new template interactively
;;
;; Defining templates:
;;
;;   Call `steven-template-define' with an active region to capture the region
;;   as the template body, or without a region to type the body at a prompt.
;;   You are always asked for a name.  Templates are persisted to
;;   `steven-templates-file' and reloaded automatically on next startup.
;;
;; Embark integration:
;;
;;   With embark installed, you can bind `steven-template-define' to
;;   `embark-region-map' to define a template directly from any active region:
;;
;;     (keymap-set embark-region-map "T" #'steven-template-define)
;;
;;   When invoked via embark-act on a region, the region text is pre-filled
;;   into the body prompt (which you can edit before confirming), and the name
;;   prompt is always left for interactive input.
;;
;; Configuration:
;;
;;   (setq steven-templates-file "~/my-templates.el")  ; custom storage path

;;; Code:

(require 'consult)

;;; Custom variables

(defcustom steven-templates '()
  "Alist of (NAME . TEMPLATE) pairs for `steven-template-insert'.
NAME is a short descriptive string.  TEMPLATE is the text to insert."
  :type '(repeat (cons string string))
  :group 'steven)

(defcustom steven-templates-file
  (expand-file-name "templates.el" user-emacs-directory)
  "File used to persist templates defined with `steven-template-define'.
The file is loaded on startup (if it exists) and rewritten on every
call to `steven-template-define'."
  :type 'file
  :group 'steven)

;;; Persistence

(when (file-exists-p steven-templates-file)
  (load steven-templates-file nil t))

(defun steven--templates-save ()
  "Write `steven-templates' to `steven-templates-file'."
  (with-temp-file steven-templates-file
    (insert ";; Auto-generated by steven-templates.el -*- lexical-binding: t -*-\n")
    (insert "(setq steven-templates '")
    (pp steven-templates (current-buffer))
    (insert ")\n")))

;;; Define command

;;;###autoload
(defun steven-template-define (name body)
  "Add or replace a template in `steven-templates' and persist it.
If the region is active, use it as the template body; otherwise prompt
for a string.  Always prompt for NAME.  On name collision, ask for
confirmation before overwriting.  The mark is deactivated after capture."
  (interactive
   (let* ((region-text (when (use-region-p)
                         (prog1 (buffer-substring-no-properties
                                 (region-beginning) (region-end))
                           (deactivate-mark))))
          (body (minibuffer-with-setup-hook
                    (lambda () (when region-text (insert region-text)))
                  (read-string "Template body: ")))
          (name (read-string "Template name: ")))
     (list name body)))
  (if-let* ((cell (assoc name steven-templates)))
      (when (y-or-n-p (format "Template %S already exists. Overwrite? " name))
        (setcdr cell body)
        (steven--templates-save)
        (message "Template %S updated." name))
    (add-to-list 'steven-templates (cons name body) t)
    (steven--templates-save)
    (message "Template %S saved." name)))

;;; Internal preview state

(defun steven--template-preview (start end candidates)
  "Return a consult state function that previews the template body.
The preview is shown as an overlay between START and END using the
`consult-preview-insertion' face.  The template body is looked up by
matching the (property-stripped) candidate name against CANDIDATES."
  (unless (or (minibufferp)
              (not (eq (window-buffer) (current-buffer))))
    (let (ov)
      (lambda (action cand)
        (cond
         ((and (not cand) ov)
          (delete-overlay ov)
          (setq ov nil))
         ((and (eq action 'preview) cand)
          ;; cand has been stripped of text properties by consult, so look up
          ;; the original candidate from the list to retrieve steven--body.
          (let* ((original (car (member cand candidates)))
                 (body (and original (get-text-property 0 'steven--body original))))
            (when body
              (unless ov
                (setq ov (consult--make-overlay start end
                                                'invisible t
                                                'window (selected-window))))
              (let ((disp (copy-sequence body)))
                (add-face-text-property 0 (length disp)
                                        'consult-preview-insertion t disp)
                (overlay-put ov 'before-string disp))))))))))

;;; Interactive command

;;;###autoload
(defun steven-template-insert ()
  "Select a template by name with live preview and insert it at point."
  (interactive)
  (let* ((start (point))
         (candidates
          (mapcar (lambda (pair)
                    (let ((name (copy-sequence (car pair))))
                      (put-text-property 0 1 'steven--body (cdr pair) name)
                      name))
                  steven-templates))
         (selected
          (consult--read
           candidates
           :prompt "Insert template: "
           :sort nil
           :require-match t
           :category 'steven-template
           :lookup #'consult--lookup-member
           :annotate (lambda (cand)
                       (when-let* ((body (get-text-property 0 'steven--body cand)))
                         (concat "  "
                                 (truncate-string-to-width
                                  (replace-regexp-in-string "\n" "↵" body)
                                  60 nil nil t))))
           :state (steven--template-preview start start candidates))))
    (when selected
      (insert (get-text-property 0 'steven--body selected)))))

(provide 'steven-templates)
;;; steven-templates.el ends here

